version: 2.1
jobs:
  test-and-lint:
    docker: 
      - image: circleci/node:14-bullseye-browsers
    steps:
      - checkout
      - run: 
          name: Install deps
          command: npm install
      - run:
          name: Run Eslint
          command: npm run fix:lint
      - run: 
          name: Run Tests
          command: npm run test --passWithNoTests
  deploy: 
    docker: 
      - image: circleci/node:14-bullseye-browsers
    steps:
      - checkout
      - run:
          name: Auth
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish
          command: npm publish --access=public
workflows:
  version: 2
  test-deploy:
    jobs:
      - test-and-lint
      - deploy:
          filters:
            tags: 
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
